### ISSUE TITLE
Environment Setup Improvements

### ISSUE THREAD

**Issue by changkun** [da-bu/ath2017#1]
The current setup instruction uses Anaconda 2.7 as setup base which may leads few potential problems. One of my friends was suffering the environment setup due to he installed Jupyter on macOS (probably exists on Windows and Linux) via pip3 before he install Anaconda: Jupyter only runs python3 kernel in this case, then he cannot actually use any installed package from Anaconda.

A more pythonic way for environment setup is to use `virtualenv` that much more clean and more **lightweight** (Anaconda is too big) for everyone in presentation workshop, few commands solves everything:

1. setup `virtualenv` for this project:

```bash
$ pip3 install virtualenv
# create virtual environment folder and explicitly specify python version
$ virtualenv venv --python=python  
$ source venv/bin/activate
(venv) $ python --version          # output is python 2.7.x
```

2. install all dependencies:
```bash
# req.txt should be provided by presenter for python project via `pip freeze > req.txt`
(venv) $ pip install -r req.txt 
```

3. run Jupyter in this virtual environment:
```bash
(venv) $ venv/bin/jupyter notebook
```

4. exit virtual environtment:

```bash
(venv) $ deactivate
$ clear
```

**Comment by da-bu** [comment]
Thanks for the alternative setup for people with Python already installed!
I expected that most people do not have/know Python beforehand.

**Comment by changkun** [comment]
Oh, probably this issue distinguish users between Windows and macOS since macOS has python preinstalled on every Mac but Windows doesn't...
